import {ScreenSpaceGI} from './screen-space-gi.js';
import {SceneGlare} from './scene-glare.js';
import { SourceGizmo } from './source-gizmo.js';
import { SceneSlices } from './scene-slices.js';
import { projectorBasis } from './scene-math.js';
/* WebGL point-projector preview. The optical detector map remains backend data. */
export class ProjectionScene {
 constructor(canvas) {
  this.panOffset=[0,0,0];this.canvas=canvas; const gl=this.gl=canvas.getContext('webgl2',{alpha:false,antialias:true,preserveDrawingBuffer:true}); if(!gl) throw Error('WebGL2 required');
  const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
  const make=(v,f)=>{const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,v));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p};
  this.program=make(`#version 300 es
   precision highp float;layout(location=0)in vec3 position;layout(location=1)in vec3 normal;uniform vec3 eye,right,up,forward;uniform float aspect;uniform bool flatView;out vec3 p;out vec3 n;
   void main(){p=position;n=normal;if(flatView){gl_Position=vec4(position.xy,0.,1.);}else{vec3 q=p-eye;float z=dot(q,forward);gl_Position=vec4(dot(q,right)*1.6/aspect,dot(q,up)*1.6,(500.001*z-1.)/499.999,z);}}`,
   `#version 300 es
   precision highp float;precision highp sampler2D;
   in vec3 p;in vec3 n;layout(location=0)out vec4 color;layout(location=1)out vec4 encodedNormal;uniform bool captureGI;
   uniform sampler2D field,shadowMap;uniform vec3 sourcePos[8],sourceForward[8],sourceRight[8],sourceUp[8];
   uniform mat4 lightVP[8];uniform float gains[8],shadowNear[8],shadowFar[8];uniform int lightCount;
   uniform float distanceM,fieldM,exposure,ambient;uniform bool flatView,hasMap,hasColor,shadowEnabled;
   vec3 mapColor(vec2 uv){vec4 t=texture(field,uv);return hasColor?t.rgb:vec3(t.r);}
   vec3 tone(vec3 v){float peak=max(.000001,max(v.r,max(v.g,v.b)));return v/peak*(1.-exp(-peak*exposure));}
   float shadow(vec3 point,int i){if(!shadowEnabled)return 1.;vec4 q=lightVP[i]*vec4(point,1.);if(q.w<=0.)return 1.;q.xyz=q.xyz/q.w*.5+.5;if(any(lessThan(q.xyz,vec3(0.)))||any(greaterThan(q.xyz,vec3(1.))))return 1.;vec2 tile=vec2(float(i%4),float(i/4));float stored=texture(shadowMap,(q.xy+tile)/vec2(4.,2.)).r;float nearZ=shadowNear[i],farZ=shadowFar[i];float current=nearZ*farZ/(farZ-q.z*(farZ-nearZ));float nearest=nearZ*farZ/(farZ-stored*(farZ-nearZ));float bias=.001+.002*(1.-abs(dot(normalize(n),-normalize(p-sourcePos[i]))));return current-bias<nearest?1.:0.;}
   void main(){encodedNormal=vec4(normalize(n)*.5+.5,1.);if(flatView){vec3 c=hasMap?mapColor(p.xy*.5+.5):vec3(0.);color=vec4(pow(tone(c),vec3(1./2.2)),1.);return;}
    vec3 sum=ambient*vec3(.018,.024,.026)*(.25+.75*abs(dot(normalize(n),normalize(vec3(.4,.8,-.5)))))/.08;
    for(int i=0;i<8;i++){if(i>=lightCount)break;if(gains[i]<=0.)continue;vec3 rel=p-sourcePos[i];float axial=dot(rel,sourceForward[i]),range=length(rel);if(axial<=.0001)continue;
      vec2 uv=vec2(dot(rel,sourceRight[i]),dot(rel,sourceUp[i]))*distanceM/(axial*fieldM)+.5;
      if(any(lessThan(uv,vec2(0.)))||any(greaterThan(uv,vec2(1.)))||!hasMap)continue;
      float incidence=abs(dot(normalize(n),-normalize(rel))),axisCos=max(.001,axial/range);
      sum+=mapColor(uv)*pow(distanceM/axial,2.)*incidence/axisCos*shadow(p,i)*gains[i];
    }color=vec4(captureGI?sum:pow(tone(sum),vec3(1./2.2)),1.);
   }`);
  this.depthProgram=make(`#version 300 es
   precision highp float;layout(location=0)in vec3 position;uniform mat4 lightVP;void main(){gl_Position=lightVP*vec4(position,1.);}`,`#version 300 es
   precision highp float;void main(){}`);
  this.vao=gl.createVertexArray();this.vbo=gl.createBuffer();gl.bindVertexArray(this.vao);gl.bindBuffer(gl.ARRAY_BUFFER,this.vbo);gl.enableVertexAttribArray(0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);
  this.texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.texture);const floatLinear=!!gl.getExtension('OES_texture_float_linear');for(const p of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,p,floatLinear?gl.LINEAR:gl.NEAREST);for(const p of [gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,p,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,1,1,0,gl.RGBA,gl.FLOAT,new Float32Array([0,0,0,1]));
  this.shadowTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadowTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,4096,2048,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);for(const p of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,p,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.shadowFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.shadowTexture,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Shadow framebuffer unavailable');gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  this.giRenderer=new ScreenSpaceGI(gl,make);this.glareRenderer=new SceneGlare(gl,make);
  this.params={ambient:1,glare:true,sourceOverlay:true,distanceM:1,fieldM:.6,exposure:.08,yaw:.12,pitch:.18,zoom:1.3,objects:false,flatView:false,hasMap:false,hasColor:false,sceneMode:'bench',lightX:0,lightY:0,lightZ:0,lightYaw:0,lightPitch:0};this.bench=this.makeBench();this.flat={vertices:new Float32Array([-1,-1,0,0,0,-1,1,-1,0,0,0,-1,1,1,0,0,0,-1,-1,-1,0,0,0,-1,1,1,0,0,0,-1,-1,1,0,0,0,-1]),count:6,bounds:{min:[-1,-1,0],max:[1,1,0]}};this.mesh=this.bench;this.model=null;this.fit={center:[0,0,.6],radius:1};this.shadowKey='';this.marker=document.createElement('span');this.marker.className='projector-marker';this.marker.title='Projector position';canvas.parentElement.append(this.marker);
  this.sliceRenderer=new SceneSlices(gl);
  this.gizmo=new SourceGizmo(canvas,{begin:()=>this.onTransformStart?.(),change:(i,pose)=>this.onTransformSource?.(i,pose),end:cancel=>this.onTransformEnd?.(cancel)});
  const pointers=new Map();canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{e.preventDefault();canvas.focus();pointers.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=canvas.onpointercancel=e=>pointers.delete(e.pointerId);canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const before=[...pointers.values()],old=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const after=[...pointers.values()];this.pan((after[0][0]+after[1][0]-before[0][0]-before[1][0])/2,(after[0][1]+after[1][1]-before[0][1]-before[1][1])/2);const distance=a=>Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);this.params.zoom=Math.max(.35,Math.min(5,this.params.zoom*distance(before)/Math.max(1,distance(after))));this.draw()}else if(pointers.size===1){if(e.shiftKey||(e.buttons&6)){this.pan(e.clientX-old[0],e.clientY-old[1]);this.draw();return}this.params.yaw-=(e.clientX-old[0])*.005;this.params.pitch=Math.max(-.8,Math.min(1.25,this.params.pitch+(e.clientY-old[1])*.004));this.draw()}};canvas.onwheel=e=>{e.preventDefault();this.params.zoom=Math.max(.35,Math.min(5,this.params.zoom*Math.exp(e.deltaY*.001)));this.draw()};canvas.tabIndex=0;canvas.onkeydown=e=>{let used=true;if(e.shiftKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){this.pan(e.key==='ArrowLeft'?-20:e.key==='ArrowRight'?20:0,e.key==='ArrowUp'?-20:e.key==='ArrowDown'?20:0)}else if(e.key==='ArrowLeft')this.params.yaw+=.04;else if(e.key==='ArrowRight')this.params.yaw-=.04;else if(e.key==='ArrowUp')this.params.pitch=Math.min(1.25,this.params.pitch+.04);else if(e.key==='ArrowDown')this.params.pitch=Math.max(-.8,this.params.pitch-.04);else if(e.key==='+'||e.key==='=')this.params.zoom=Math.max(.35,this.params.zoom*.94);else if(e.key==='-')this.params.zoom=Math.min(5,this.params.zoom/.94);else used=false;if(used){e.preventDefault();this.draw()}};window.addEventListener('resize',()=>this.draw());this.resizeObserver=new ResizeObserver(()=>this.draw());this.resizeObserver.observe(canvas);this.draw();
 }
 focusSlices(){const planes=this.sliceRenderer.planes;if(!planes.length)return;const source=this.basis(),lo=Math.min(...planes.map(p=>p.z)),hi=Math.max(...planes.map(p=>p.z));this.fit={center:source.position.map((v,i)=>v+source.forward[i]*(lo+hi)/2),radius:Math.max(.005,Math.hypot(this.sliceRenderer.field/Math.sqrt(2),(hi-lo)/2))};this.panOffset=[0,0,0];this.params.zoom=1.8;this.draw()}
 setSlices(slices,field,enabled,opacity=.65){this.sliceRenderer.set(slices,field);this.showSlices=enabled;this.sliceOpacity=opacity;this.draw()}
 makeBench(f=this.params.fieldM,d=this.params.distanceM,objects=this.params.objects){const v=[],tri=(a,b,c,n)=>[a,b,c].forEach(p=>v.push(...p,...n)),quad=(a,b,c,e,n)=>{tri(a,b,c,n);tri(a,c,e,n)},front=Math.max(.001,d-f*1.3),x=.65*f,y=.5*f;quad([-x,-y,d],[x,-y,d],[x,y,d],[-x,y,d],[0,0,-1]);quad([-x,-y,front],[x,-y,front],[x,-y,d],[-x,-y,d],[0,1,0]);quad([-x,-y,front],[-x,-y,d],[-x,y,d],[-x,y,front],[1,0,0]);quad([x,-y,d],[x,-y,front],[x,y,front],[x,y,d],[-1,0,0]);if(objects){const c=[-.2*f,-.32*f,.77*d],r=.15*f,point=(i,j)=>{const a=i/14*Math.PI,b=j/20*Math.PI*2;return [Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)]};for(let i=0;i<14;i++)for(let j=0;j<20;j++)for(const q of [[i,j],[i+1,j],[i+1,j+1],[i,j],[i+1,j+1],[i,j+1]]){const n=point(...q);v.push(...n.map((z,k)=>c[k]+r*z),...n)}const center=[.23*f,-.36*f,.66*d],size=[.1*f,.14*f,.1*f];for(let a=0;a<3;a++)for(const s of [-1,1]){let n=[0,0,0];n[a]=s;let p=[];for(const [u,w]of [[-1,-1],[1,-1],[1,1],[-1,1]]){let z=[...center];z[a]+=s*size[a];z[(a+1)%3]+=u*size[(a+1)%3];z[(a+2)%3]+=w*size[(a+2)%3];p.push(z)}quad(...p,n)}}return {vertices:new Float32Array(v),count:v.length/6,bounds:{min:[-x,-y,front],max:[x,y,d]}}}
 async loadModel(url='assets/demo-scene.json'){if(this.modelPromise)return this.modelPromise;this.modelPromise=(async()=>{const raw=await (await fetch(url)).json(),base=url.slice(0,url.lastIndexOf('/')+1);const floats=async file=>new Float32Array(await (await fetch(base+file)).arrayBuffer());const p=raw.positions_file?await floats(raw.positions_file):new Float32Array(raw.positions),n=raw.normals_file?await floats(raw.normals_file):(raw.normals?new Float32Array(raw.normals):null),v=new Float32Array(p.length*2);for(let i=0;i<p.length;i+=3){const o=i*2;v[o]=p[i];v[o+1]=p[i+2];v[o+2]=-p[i+1];v[o+3]=n?n[i]:0;v[o+4]=n?n[i+2]:1;v[o+5]=n?-n[i+1]:0}const b=raw.content_bounds||raw.bounds||{min:[-1,-1,-1],max:[1,1,1]},min=[b.min[0],b.min[2],-b.max[1]],max=[b.max[0],b.max[2],-b.min[1]],center=min.map((x,i)=>(x+max[i])/2),radius=Math.max(.2,Math.hypot(...max.map((x,i)=>x-min[i]))/2),suggestedLight={lightX:center[0],lightY:center[1],lightZ:min[2]-radius*1.15,lightYaw:0,lightPitch:0};const rec=raw.lights?.recommended_projector;if(rec?.position&&rec?.target){const a=[rec.position[0],rec.position[2],-rec.position[1]],b=[rec.target[0],rec.target[2],-rec.target[1]],direction=norm(b.map((x,i)=>x-a[i]));Object.assign(suggestedLight,{lightX:a[0],lightY:a[1],lightZ:a[2],lightYaw:Math.atan2(direction[0],direction[2])*180/Math.PI,lightPitch:Math.min(89,Math.asin(direction[1])*180/Math.PI)});}this.model={vertices:v,count:v.length/6,bounds:{min,max},shadowBounds:raw.bounds?{min:[raw.bounds.min[0],raw.bounds.min[2],-raw.bounds.max[1]],max:[raw.bounds.max[0],raw.bounds.max[2],-raw.bounds.min[1]]}:{min,max},meta:raw};if(this.params.sceneMode==='model'){this.fitView();this.draw();}return {bounds:{min,max},triangles:raw.triangle_count||v.length/18,source:raw.source||null,suggestedLight};})();try{return await this.modelPromise}catch(error){this.modelPromise=null;throw error}}
 set(values){Object.assign(this.params,values);this.draw()}
 upload(buffer,res,config,colorBuffer=null){const gl=this.gl;let rgba;if(colorBuffer){const src=new Float32Array(colorBuffer);rgba=src.length===res*res*4?src:new Float32Array(res*res*4);this.params.hasColor=src.length===res*res*4;}else{const src=new Float32Array(buffer);rgba=new Float32Array(res*res*4);for(let i=0;i<src.length;i++)rgba.set([src[i],src[i],src[i],1],i*4);this.params.hasColor=false;}const tint=[0,0,0];for(let i=0;i<rgba.length;i+=4)for(let j=0;j<3;j++)tint[j]+=Math.max(0,rgba[i+j]);const peak=Math.max(...tint);this.params.glareTint=tint.map(v=>peak>0?v/peak:0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,res,res,0,gl.RGBA,gl.FLOAT,rgba);this.set({hasMap:true,distanceM:config.detector_z_mm/1000,fieldM:config.detector_size_mm/1000})}
 pan(dx,dy){if(this.params.flatView)return;const P=this.params,forward=norm([-Math.sin(P.yaw)*Math.cos(P.pitch),-Math.sin(P.pitch),Math.cos(P.yaw)*Math.cos(P.pitch)]),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),scale=2*this.fit.radius*P.zoom/(1.6*Math.max(1,this.canvas.clientHeight));this.panOffset=this.panOffset.map((v,i)=>v+(-dx*right[i]+dy*up[i])*scale)}
 fitView(){this.panOffset=[0,0,0];const active=this.params.sceneMode==='model'&&this.model?this.model:this.makeBench(),b=active.bounds,c=b.min.map((x,i)=>(x+b.max[i])/2),r=Math.max(.005,Math.hypot(...b.max.map((x,i)=>x-b.min[i]))/2);this.fit={center:c,radius:r};this.params.yaw=.55;this.params.pitch=.28;this.params.zoom=1.5;this.draw();return {center:[...c],radius:r,yaw:this.params.yaw,pitch:this.params.pitch,zoom:this.params.zoom}}
 aimAtCenter(){return {target:[...this.fit.center],...this.fitView()}}
 basis(){const P=this.params;if(P.sceneLights?.length)return P.sceneLights[P.activeSceneSource||0]||P.sceneLights[0];return {...projectorBasis(P.lightYaw,P.lightPitch),position:[P.lightX,P.lightY,P.lightZ]}}
 shadowMatrix(source){const P=this.params,b=this.mesh.shadowBounds||this.mesh.bounds,far=Math.max(3,...Array.from({length:8},(_,i)=>Math.hypot(...b.min.map((x,j)=>(i&(1<<j)?b.max[j]:x)-source.position[j]))))+2;this.shadowNear=.005;this.shadowFar=far;const target=source.position.map((x,i)=>x+source.forward[i]),view=lookAt(source.position,target,source.up),fov=2*Math.atan(P.fieldM/(2*Math.max(.001,P.distanceM)));return multiply(perspective(Math.max(.02,fov),1,this.shadowNear,far),view);}

 updateMesh(){const gl=this.gl,P=this.params,benchKey=[P.fieldM,P.distanceM,P.objects].join(',');if(this.benchKey!==benchKey){this.bench=this.makeBench();this.benchKey=benchKey;if(P.sceneMode==='bench'){const b=this.bench.bounds;this.fit={center:b.min.map((x,i)=>(x+b.max[i])/2),radius:Math.max(.005,Math.hypot(...b.max.map((x,i)=>x-b.min[i]))/2)}}}const next=P.flatView?this.flat:(P.sceneMode==='model'&&this.model?this.model:this.bench);if(next===this.mesh&&this.meshKey===next.vertices)return;this.mesh=next;this.meshKey=next.vertices;gl.bindBuffer(gl.ARRAY_BUFFER,this.vbo);gl.bufferData(gl.ARRAY_BUFFER,next.vertices,gl.STATIC_DRAW);this.shadowKey=''}
 renderShadow(lightVP,key){if(this.shadowKey===key)return;const gl=this.gl;this.shadowKey=key;gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFbo);gl.viewport(0,0,1024,1024);gl.clear(gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.useProgram(this.depthProgram);gl.bindVertexArray(this.vao);gl.uniformMatrix4fv(gl.getUniformLocation(this.depthProgram,'lightVP'),false,lightVP);gl.drawArrays(gl.TRIANGLES,0,this.mesh.count);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
 draw(){
  const gl=this.gl,c=this.canvas,P=this.params,scale=Math.min(devicePixelRatio,1.5),w=Math.max(1,Math.round(c.clientWidth*scale)),h=Math.max(1,Math.round(c.clientHeight*scale));
  if(c.width!==w||c.height!==h){c.width=w;c.height=h;}this.updateMesh();
  const lights=P.sceneLights?.length?P.sceneLights.slice(0,8):[{...this.basis(),gain:1}],source=this.basis();
  const shadows=lights.map(light=>{const matrix=this.shadowMatrix(light);return {matrix,near:this.shadowNear,far:this.shadowFar};});
  const key=JSON.stringify([P.sceneMode,P.fieldM,P.distanceM,this.mesh.count,lights.map(l=>[l.position,l.forward])]);
  if(!P.flatView&&this.shadowKey!==key){
   this.shadowKey=key;gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFbo);gl.viewport(0,0,4096,2048);gl.clear(gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.useProgram(this.depthProgram);gl.bindVertexArray(this.vao);
   shadows.forEach((shadow,i)=>{gl.viewport((i%4)*1024,Math.floor(i/4)*1024,1024,1024);gl.uniformMatrix4fv(gl.getUniformLocation(this.depthProgram,'lightVP'),false,shadow.matrix);gl.drawArrays(gl.TRIANGLES,0,this.mesh.count);});gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  }
  const captureGI=!!P.ssgi&&!P.flatView&&this.giRenderer.begin(w,h);
  gl.viewport(0,0,w,h);gl.useProgram(this.program);gl.bindVertexArray(this.vao);
  const loc=k=>gl.getUniformLocation(this.program,k),target=this.fit.center.map((v,i)=>v+this.panOffset[i]),offset=[Math.sin(P.yaw)*Math.cos(P.pitch),Math.sin(P.pitch),-Math.cos(P.yaw)*Math.cos(P.pitch)].map(x=>x*this.fit.radius*P.zoom),eye=target.map((x,i)=>x+offset[i]),forward=norm(offset.map(x=>-x)),right=norm(cross(forward,[0,1,0])),up=cross(right,forward);
  for(const[k,v]of Object.entries({eye,forward,right,up}))gl.uniform3fv(loc(k),v);
  lights.forEach((light,i)=>{for(const[k,v]of Object.entries({sourcePos:light.position,sourceForward:light.forward,sourceRight:light.right,sourceUp:light.up}))gl.uniform3fv(loc(k+'['+i+']'),v);gl.uniform1f(loc('gains['+i+']'),light.gain);gl.uniformMatrix4fv(loc('lightVP['+i+']'),false,shadows[i].matrix);gl.uniform1f(loc('shadowNear['+i+']'),shadows[i].near);gl.uniform1f(loc('shadowFar['+i+']'),shadows[i].far);});
  gl.uniform1i(loc('lightCount'),lights.length);gl.uniform1f(loc('aspect'),w/h);gl.uniform1f(loc('distanceM'),P.distanceM);gl.uniform1f(loc('fieldM'),P.fieldM);gl.uniform1f(loc('exposure'),P.exposure);gl.uniform1f(loc('ambient'),P.ambient);
  for(const k of ['flatView','hasMap','hasColor'])gl.uniform1i(loc(k),P[k]?1:0);gl.uniform1i(loc('shadowEnabled'),!P.flatView&&(P.sceneMode==='model'||P.objects)?1:0);
  gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.uniform1i(loc('field'),0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.shadowTexture);gl.uniform1i(loc('shadowMap'),1);
  gl.uniform1i(loc('captureGI'),captureGI?1:0);
  gl.enable(gl.DEPTH_TEST);gl.clearColor(.023,.033,.035,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);if(P.flatView){const side=Math.round(Math.min(w,h)*.88);gl.viewport((w-side)/2,(h-side)/2,side,side);}gl.drawArrays(gl.TRIANGLES,0,this.mesh.count);
  if(captureGI){gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.uniform1i(loc('captureGI'),0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,this.mesh.count);this.giRenderer.finish({right,up,forward},P);}
  if(this.showSlices&&!P.flatView)lights.forEach((light,i)=>{if(light.gain>0)this.sliceRenderer.draw({eye,forward,right,up,aspect:w/h},light,this.sliceOpacity,{enabled:!!P.sliceShadows,matrix:shadows[i].matrix,texture:this.shadowTexture,near:shadows[i].near,far:shadows[i].far,rect:[(i%4)/4,Math.floor(i/4)/2,1/4,1/2]},P.sliceInfill?P.infillSteps||8:1);});
  if(!P.flatView)this.glareRenderer.draw({eye,forward,right,up,width:w,height:h},lights,P,this.texture);
  this.markers??=[this.marker];while(this.markers.length<lights.length){const marker=document.createElement('span');marker.className='projector-marker';c.parentElement.append(marker);this.markers.push(marker);}
  this.markers.forEach((marker,i)=>{const light=lights[i];if(!light){marker.hidden=true;return;}const rel=light.position.map((x,j)=>x-eye[j]),z=dot(rel,forward),px=(dot(rel,right)*1.6/(w/h)/z*.5+.5)*c.clientWidth,py=(.5-dot(rel,up)*1.6/z*.5)*c.clientHeight;marker.hidden=!P.sourceOverlay||P.flatView||z<=0||px<0||px>c.clientWidth||py<0||py>c.clientHeight;marker.style.left=px+'px';marker.style.top=py+'px';marker.textContent=String(i+1);marker.title='Select projector '+(i+1);marker.setAttribute('role','button');marker.setAttribute('aria-label','Select projector '+(i+1));marker.tabIndex=0;marker.classList.toggle('selected',i===(P.activeSceneSource||0));marker.onpointerdown=e=>e.stopPropagation();marker.onclick=e=>{e.stopPropagation();this.onSelectSource?.(i);};marker.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.onSelectSource?.(i);}};});
  this.gizmo?.update(lights,{eye,forward,right,up,width:c.clientWidth,height:c.clientHeight},P.activeSceneSource||0,P.sourceOverlay&&!P.flatView&&P.showSourceGizmo!==false);
  c.dataset.ssgi=String(captureGI);c.dataset.ssgiSupported=String(this.giRenderer.supported);c.dataset.sourceFacing=lights.map(l=>dot(norm(eye.map((v,i)=>v-l.position[i])),l.forward).toFixed(3)).join(',');c.dataset.ambient=String(P.ambient);c.dataset.glare=String(P.glare);c.dataset.sourceOverlay=String(P.sourceOverlay);c.dataset.sliceShadows=String(!!P.sliceShadows);c.dataset.pathSlices=String(this.showSlices?this.sliceRenderer.planes.length:0);c.dataset.cameraPan=this.panOffset.join(',');c.dataset.exposureEv=String(Math.log2(P.exposure/.08));c.dataset.triangles=this.mesh.count/3;c.dataset.lightPosition=source.position.join(',');c.dataset.lightCount=String(lights.length);c.dataset.view=P.flatView?'detector':'3d';c.dataset.sceneMode=P.sceneMode;c.dataset.renderError=String(gl.getError());
 }

}
const norm=a=>{const l=Math.hypot(...a)||1;return a.map(x=>x/l)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
function lookAt(e,t,u){const z=norm(e.map((x,i)=>x-t[i])),x=norm(cross(u,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1])}
function perspective(f,a,n,fv){const q=1/Math.tan(f/2),nf=1/(n-fv);return new Float32Array([q/a,0,0,0,0,q,0,0,0,0,(fv+n)*nf,-1,0,0,2*fv*n*nf,0])}
function multiply(a,b){const r=new Float32Array(16);for(let c=0;c<4;c++)for(let row=0;row<4;row++)r[c*4+row]=a[row]*b[c*4]+a[4+row]*b[c*4+1]+a[8+row]*b[c*4+2]+a[12+row]*b[c*4+3];return r}
